version: '2'
services:
  backend:
    build: '.'
    # image: tktohjaajarek/ohjaajarekisteriback:latest
    depends_on:
      - db
    restart: unless-stopped
    ports: 
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - SECRET=aaaa
      - DATABASE_URL=postgresql://ohjaajarek:password@db:5432/ohjaajarek
  db:
    image: postgres:10.6
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ohjaajarek
      - PGDATA=/data/ohjaajarek_db
      - POSTGRES_USER=ohjaajarek
      - POSTGRES_PASSWORD=password
    volumes:
      - /data/ohjaajarek_db:/ohrek_db