version: '2'
services:
  frontend:
    build: './client'
    # image: tktohjaajarek/ohjaajarekisterifront:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - backend
      - db
  backend:
    build: './server'
    # image: tktohjaajarek/ohjaajarekisteriback:latest
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SECRET=aaaa
      - DATABASE_URL=postgresql://ohjaajarek:password@db:5432/ohjaajarek
  db:
    image: postgres:10.6
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ohjaajarek
      - PGDATA=/data/ohjaajarek_db
      - POSTGRES_USER=ohjaajarek
      - POSTGRES_PASSWORD=password
    volumes:
      - /data/ohjaajarek_db:/ohrek_db