version: '3.5'
services:
  frontend:
    build:
      context: './client'
      dockerfile: 'dev.Dockerfile'
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - backend
      - db
    environment:
      - PORT=8000
    volumes:
      - ./client:/app/
      - /app/node_modules
  backend:
    build:
      context: './server'
      dockerfile: 'dev.Dockerfile'
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - DEV_PORT=8001
      - SECRET=aaaa
      - DEV_DATABASE_URL=postgresql://ohjaajarek:password@db:5432/ohjaajarek
      - TEST_DATABASE_URL=postgresql://ohjaajarek:password@db:5432/test
    volumes:
      - ./server:/app/
      - /app/node_modules
  db:
    image: postgres:10.6
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ohjaajarek
      - PGDATA=/data/ohjaajarek_db
      - POSTGRES_USER=ohjaajarek
      - POSTGRES_PASSWORD=password
    volumes:
      - ./ohrek_db:/data/ohjaajarek_db